# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=amazonlinux

[Distribution]
Release=latest
Repositories=amazonlinux

[Content]
# The unsigned-shim package tries to install to the same location as the signed shim package so we can't install and
# test unsigned shim.
ShimBootloader=none
Packages=
        kernel-tools
